version: '3.8'

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS:  INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME:  INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  customer-servis:
    container_name: customer-servis
    build: ./customer-servis
    # network_mode: database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_USER=postgres
      - POSTGRES_DB=customer
      - POSTGRES_PASSWORD=asliddin2001
      - ENVIRONMENT=develop
      - LOG_LEVEL=develop
    depends_on:
      - 'post-service'
    ports:
      - '8810:8810'
  migrate-customer:
    image: migrate/migrate

    volumes:
      - ./customer-servis/migrations:/migrations
    command: ['-path','/migrations','-database','postgres://postgres:asliddin2001@database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com:5432/customer?sslmode=disable','up']
    depends_on:
      - 'customer-servis'
  post-service:
    container_name: post-service
    build: ./post-service
    # network_mode: host
    # network_mode: database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_USER=postgres
      - POSTGRES_DB=post
      - POSTGRES_PASSWORD=asliddin2001
      - ENVIRONMENT=develop
      - LOG_LEVEL=develop
    depends_on:
      - 'review-servise'
    ports:
      - '8820:8820'
  migrate-post:
    image: migrate/migrate

    volumes:
      - ./post-service/migrations:/migrations
    command: ['-path','/migrations','-database','postgres://postgres:asliddin2001@database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com:5432/post?sslmode=disable','up']
    depends_on:
      - post-service
  review-servise:
    container_name: review-servise
    build: ./review-servise
    # network_mode: database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_USER=postgres
      - POSTGRES_DB=review
      - POSTGRES_PASSWORD=asliddin2001
      - ENVIRONMENT=develop
      - LOG_LEVEL=develop
    ports:
      - '8840:8840'
  migrate-review:
    image: migrate/migrate
    volumes:
      - ./review-servise/migrations:/migrations
    command: ['-path','/migrations','-database','postgres://postgres:asliddin2001@database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com:5432/review?sslmode=disable','up']
    depends_on:
      - 'review-servise'
  api-gateway:
    container_name: api-gateway
    build: ./exam-api-gateway
    # network_mode: database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com

    # network_mode: host
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=asliddin2001
      - ENVIRONMENT=develop
      - LOG_LEVEL=develop
    depends_on:
      - 'post-service'
      - 'review-servise'
      - 'customer-servis'
      - 'redisdb'
      - kafka-ui
    ports:
      - '8070:8070'
  migrate-api:
    image: migrate/migrate

    volumes:
      - ./exam-api-gateway/migrations:/migrations
    command: ['-path','/migrations','-database','postgres://postgres:asliddin2001@database-1.c9lxq3r1itbt.us-east-1.rds.amazonaws.com:5432/api?sslmode=disable','up']
    depends_on:
      - api-gateway
  redisdb:
    container_name: redisdb
    image: redis:latest
    ports:
      - '6381:6379'


# networks:
#   default:
#     external:
#       name: asliddin-developer